version: '3.8'

services:
  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: backend_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend-api:/var/www
    ports:
      - "8000:8000"
    command: "php artisan serve --host 0.0.0.0"
    depends_on:
      - database
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: database
      DB_DATABASE: backend_api
      DB_USERNAME: root
      DB_PASSWORD:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: "npm run dev"
    depends_on:
      - backend

  database:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: backend_api
      MYSQL_USER: renato
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
